### ISSUE TITLE
Feature: Sleep Score Update 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Sleepometer-Android-App#17]
### Feature description

Ping on discord me for this issue , I will briefly say

![9086b317-fdf8-41de-88b3-6418dbc2f32f](https://user-images.githubusercontent.com/74618071/180864682-fc2562d4-dba1-44a6-86d6-efa9b135f320.jpg)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by Anjali2201** [comment]
Would like to contribute

**Comment by SaranshBaniyal** [comment]
is this issue still open?

**Comment by maityamit** [comment]
> is this issue still open?

Yes

**Comment by dhruvpatidar359** [comment]
@maityamit can you please 
explain the issue ?
