### ISSUE TITLE
Feature: Info Dialog box create here  (Ping on discord me for this issue , I will briefly say)

### ISSUE THREAD

**Issue by maityamit** [maityamit/Sleepometer-Android-App#18]
### Feature description

Ping on discord me for this issue , I will briefly say

![76ada822-a16b-4d5f-9da7-b938805fa58c](https://user-images.githubusercontent.com/74618071/180864899-bb4fc5f9-2ba5-4951-9379-9a9214d62a5f.jpg)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by venkat-clone** [comment]
assign me this issue
