### ISSUE TITLE
Feature: Emoji add here according to Sleep Score

### ISSUE THREAD

**Issue by maityamit** [maityamit/Sleepometer-Android-App#19]
### Feature description

Contact on discord for more info about this 
![46dba206-0a12-49bf-b00c-b7bb7bd1dece](https://user-images.githubusercontent.com/74618071/180865375-91ed9a88-53fd-41ee-bd8b-f9f582fde58b.jpg)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by vickyrules** [comment]
@maityamit  assign this

**Comment by vickyrules** [comment]
@maityamit  sorry busy with other tasks, assign someone else.

**Comment by Anjali2201** [comment]
would like to contibute to this issue.

**Comment by maityamit** [comment]
Issue Done
