### ISSUE TITLE
Want to Update Contributing.md file

### ISSUE THREAD

**Issue by MohammadKaif1** [maityamit/Sleepometer-Android-App#28]
### Description

Hey @maityamit  there is no firebase configuration steps in contributing.md file to setup new project after cloning.
Please Assign me this issue.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by SaranshBaniyal** [comment]
@MohammadKaif1  good evening sir. Can you please assign this issue to me, and also give me guidance on how to proceed with this

**Comment by maityamit** [comment]
sorry, This issue is closed due to no used.
I already mentioned in the readme file everything.
