### ISSUE TITLE
Login with Phone Number

### ISSUE THREAD

**Issue by utkarsh006** [maityamit/Sleepometer-Android-App#33]
### Feature description

- The user must be provided with an option to log in with a Phone Number.
- This can be done using Firebase authentication.
- Contributing under KWOC'22.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by musavveer** [comment]
is anyone working on this issue?? If not assign this to me.

**Comment by Interstellar07** [comment]
Is there anyone on this? If not kindly assign this to me.

**Comment by maityamit** [comment]
Hey, @musavveer are you want to do this ?

**Comment by musavveer** [comment]
> Hey, @musavveer are you want to do this ?

Yes!! Assign me this

**Comment by maityamit** [comment]
@musavveer okay
