### ISSUE TITLE
Feature: Live update Active sleep time

### ISSUE THREAD

**Issue by kuldeepsingh0330** [maityamit/Sleepometer-Android-App#36]
### Feature description

this one :- 
![1670525784271](https://user-images.githubusercontent.com/95225751/206543494-699dabc4-809a-43a4-8456-1fd7ef9e42c0.jpg)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by maityamit** [comment]
@kuldeepsingh0330 there available hrs and mnts and implement this service including add the second ...
