### ISSUE TITLE
Feature: sleep at time & wake up time update  

### ISSUE THREAD

**Issue by kuldeepsingh0330** [maityamit/Sleepometer-Android-App#38]
### Feature description

**_sleep at time & wake up time update  when we start and end the sleep._**

![Screenshot 2022-12-11 153351](https://user-images.githubusercontent.com/95225751/206897630-d471c561-ab82-44f5-990a-9a9d7ad42fbf.png)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by maityamit** [comment]
great, this will be like the previous day's timings 
when the button is pressed for sleep and when the sleep end catches this and shows it here...

and when sleep start then set the sleep end text as "sleeping" and set the sleep at the time, after pressing wakes up then update the wake-up text view.

**Comment by kuldeepsingh0330** [comment]
I think when sleep start then set the sleep end text as "--:--"

tell me which text i should use
