### ISSUE TITLE
[Bug]:  app crash in "stats Fragement"

### ISSUE THREAD

**Issue by kuldeepsingh0330** [maityamit/Sleepometer-Android-App#44]
### Contact Details

kuldeepsingh030020001@gmail.com

### What happened?

A bug happened!

https://user-images.githubusercontent.com/95225751/207600603-7083d1f9-f489-4418-a578-3ac3297e7870.mp4

![1](https://user-images.githubusercontent.com/95225751/207600632-8c9bb771-f00f-40e2-bb71-aa56a39cb37d.png)

When I was switch between stats and Home fragement.  The app was crashed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rohit-554** [comment]
Basically when you are setting the colour it needs the current context, so you can use the below code 
Use
serires.ContextCompat.getColor(requirecontext, R.color.purple_700);

See if this works!

**Comment by maityamit** [comment]
@kuldeepsingh0330 
now works ?

**Comment by kuldeepsingh0330** [comment]
yes and i have solved the issue

**Comment by kuldeepsingh0330** [comment]
yes and i have solved the issue

**Comment by kuldeepsingh0330** [comment]
assign me this issue and i created a PR.

**Comment by Rohit-554** [comment]
@maityamit Amit Bhaiya can you share your social media profile! I want to have some experience from you ☺️

**Comment by maityamit** [comment]
okay @kuldeepsingh0330
