### ISSUE TITLE
[Bug]: In Dark mode, Most of the content is not showing

### ISSUE THREAD

**Issue by Suryansh1720001** [maityamit/Sleepometer-Android-App#46]
### Contact Details

suryansh7202@gmail.com

### What happened?

A bug happened!

.<img src= "https://user-images.githubusercontent.com/85965606/208282778-b0cd493f-39b2-4eef-8dab-ee22392947f8.png" width="250" height="505">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rizwan102003** [comment]
I can try to fix this problem. Can the mentor assign me to this......

**Comment by AbhinavJD7** [comment]
Hello, I can try to fix this problem. So ,can you please assign me this project @maityamit

**Comment by Suryansh1720001** [comment]
Hello @maityamit 
Assign this issue to me as I found this bug and report it here.
Thank You

**Comment by maityamit** [comment]
As per the queue, Assign: @Rizwan102003 , if you want to continue with this, please comment or I will assign another one.

**Comment by maityamit** [comment]
@Rizwan102003 you want to do this ?

**Comment by Rizwan102003** [comment]
Heyy @maityamit , u can assign it to me and i can try taking care of the bug. But i had one question, don't we need to wait till 15th for getting assigned and doing the projects?

**Comment by maityamit** [comment]
@Rizwan102003 You participating JGEC Winter of Code ?

**Comment by Rizwan102003** [comment]
@maityamit Sir yes sir 😂
