### ISSUE TITLE
Feature: Splash Screen UI Redesign in XML

### ISSUE THREAD

**Issue by maityamit** [maityamit/Sleepometer-Android-App#5]
## [Figma Link](https://www.figma.com/file/v15ij8Fy57aS40Fvn2vj7W/Sleep-Meter?node-id=105%3A2)

<img src="https://user-images.githubusercontent.com/74618071/178523749-f8496f81-3bfd-42e8-8fdc-3c626d4336f3.png" width="30%">

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by aritra-tech** [comment]
Can you assign it to me

**Comment by maityamit** [comment]
From official Timeline I will assign.

**Comment by aritra-tech** [comment]
Ok ok

**Comment by vickyrules** [comment]
@maityamit Please assign this to me.

**Comment by maityamit** [comment]
@vickyrules as per first cim first serve , I will assign this to aritra. 
You can find another issue in the app and create, If validate i will assisn .

**Comment by aritra-tech** [comment]
I am unassigning myself @maityamit give it to @vickyrules 
Sorry

**Comment by vickyrules** [comment]
> I am unassigning myself @maityamit give it to @vickyrules Sorry

@maityamit

**Comment by vickyrules** [comment]
@maityamit 
do you have any ideas or suggestions regarding this issue?

**Comment by maityamit** [comment]
@vickyrules there is already a splash screen. 
You just need to redesign according to given image . On that XML file
