### ISSUE TITLE
Feature: A new and good looking UI for the settings tab of the app

### ISSUE THREAD

**Issue by aryanmishra29** [maityamit/Sleepometer-Android-App#59]
### Feature description

The settings section of the app needs a new finish. The UI needs an update. 
I will make a clean but attractive UI for this tab following the colour code of the app i.e. Blue and White.
![d26bd2c8-896d-4333-9922-8b32056140ea](https://user-images.githubusercontent.com/92439461/216848228-7bd67120-b1ba-4e20-934f-a36170636895.jpeg)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by aryanmishra29** [comment]
@maityamit Kindly review and assign this feature to me under IWOC label.

**Comment by maityamit** [comment]
Okay, You can continue ....
