### ISSUE TITLE
Feature: Background Color Change of the whole app 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Sleepometer-Android-App#6]
### Feature description

Figma: https://www.figma.com/file/v15ij8Fy57aS40Fvn2vj7W/Sleep-Meter?node-id=0%3A1

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by vickyrules** [comment]
@maityamit please assign this issue to me.

**Comment by maityamit** [comment]
@vickyrules ping me on discord on Sleepometer grp , I will give some more insights to integrate this 👍
