### ISSUE TITLE
Feature: Alarm Feature add in the app

### ISSUE THREAD

**Issue by maityamit** [maityamit/Sleepometer-Android-App#7]
### Feature description

Create a alarm feauture 

Please contact me before implementing this. 
we need to discuss that. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by binayshaw7777** [comment]
I want to working on this issue! @maityamit

**Comment by JOYPAUL2001** [comment]
I want to work on this issue. @maityamit

**Comment by loanwolf0** [comment]
hello sir ,  i want to contribute on this please assign it to me so that i work on it and learn something from it .

**Comment by maityamit** [comment]
@loanwolf0  according to first cum first serve I assign to @JOYPAUL2001

**Comment by loanwolf0** [comment]
ok no prblm
