### ISSUE TITLE
Changing LinkedIn logo 

### ISSUE THREAD

**Issue by UjjwalMahar** [maityamit/Sleepometer-Android-App#71]
### Feature description

 
![IMG_20230211_112425](https://user-images.githubusercontent.com/111011580/218242975-962f7e9f-578b-43cd-92bf-4c77f61ffb26.jpg)

LinkedIn logo is matching with the background.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by maityamit** [comment]
Now, there is no need for this logo. I will remove this linkedin function. 
Only GitHub will be there.

**Comment by UjjwalMahar** [comment]
Great
