### ISSUE TITLE
Documentation: Flow of Control

### ISSUE THREAD

**Issue by A91y** [maityamit/Sleepometer-Android-App#73]
### Description

A **Flow of Control** need to be added in Readme to make user understand how to use the website and various functionalities of it.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by A91y** [comment]
Please assign me issue under iwoc and easy/medium/hard.

**Comment by Tavish108** [comment]
Please assign me issue under iwoc and easy/medium/hard

**Comment by A91y** [comment]
> Please assign me issue under iwoc and easy/medium/hard

I am already working on it and almost completed.

**Comment by A91y** [comment]
This issue is solved in PR #75. Please close it.

**Comment by maityamit** [comment]
Okay @A91y
