### ISSUE TITLE
Documentation: Updating CONTRIBUTING.md

### ISSUE THREAD

**Issue by A91y** [maityamit/Sleepometer-Android-App#74]
### Description

Few mistakes are found in this file and need to be updated.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by A91y** [comment]
Please assign me this issue under iwoc and easy/medium/hard.

**Comment by maityamit** [comment]
@A91y Okay, continue :)
