### ISSUE TITLE
Documentation: Update Readme file new features

### ISSUE THREAD

**Issue by Suryansh1720001** [maityamit/Sleepometer-Android-App#78]
### Description

Hello @maityamit 

## Features I want to add - 
- add the contribution guidelines.
- Add the maintainer details
- Add new features for more attractiveness

These are important features of the readme file of any open-source project. kindly assign me this issue.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by maityamit** [comment]
JWOC or iwoc ?? @Suryansh1720001

**Comment by Suryansh1720001** [comment]
Iwoc

**Comment by maityamit** [comment]
@Suryansh1720001 continue, but be careful about readme.
By the way, I will check ...

**Comment by Code1705** [comment]
Hey !...@maityamit  I want to contribute to this issue by making a proper readme file as per your requirements nd attractive too, please assign me under Jwoc.
