### ISSUE TITLE
Feature: Create this Like UI using XML 

### ISSUE THREAD

**Issue by maityamit** [maityamit/Sleepometer-Android-App#8]
### Feature description

Contact me I will say details 

![011b1e96-c344-40c2-a1be-9fb39081da3a](https://user-images.githubusercontent.com/74618071/179087205-5490df99-0a16-462a-8df7-942b93282823.jpg)

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by loanwolf0** [comment]
I want to contribute in your project , i created some nice ui designs for my underdeveloped application .
If nobody is working on this issue then please assign it to me i want to learn something from your project ,
so please assign it to me i will you mind-blowing results .

how can i contact to you , please provide me details .

**Comment by maityamit** [comment]
@loanwolf0 Contact me on Hsoc discord group, you can see there is a channel called Sleepometer. 
There you can ping me.

**Comment by loanwolf0** [comment]
i am sorry but can we connect by 
1. email :- " anurag12776@gmail.com " , 
2. any discord channel .
3.  i cant not connect with you by Hsoc because i did not anything know about it .

**Comment by maityamit** [comment]
@loanwolf0 are you on the HackClub RAIT discord channel?

**Comment by maityamit** [comment]
@loanwolf0  There you can see a channel called Sleepometer, You can reach out there.

**Comment by maityamit** [comment]
![Screenshot 2022-07-16 144430](https://user-images.githubusercontent.com/74618071/179348723-0c6ae191-da40-4823-b327-c32296693c8b.png)


@loanwolf0
