### ISSUE TITLE
[Bug]: Gave Corner Radius to the Google Signin Image using CardView

### ISSUE THREAD

**Issue by maityamit** [maityamit/Sleepometer-Android-App#80]
### Contact Details

maityamit308@gmail.com

### What happened?

A bug happened!
[Bug]: Gave Corner Radius to the Google Signin Image using CardView
``` activity_login.xml ```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ajeeshrawal** [comment]
@maityamit please assign this issue

**Comment by maityamit** [comment]
@ajeeshrawal  you can use cardview
( Iwoc or JGEC Winter of code ?)

**Comment by ajeeshrawal** [comment]
IWoC sir

**Comment by ajeeshrawal** [comment]
#86 pull request created @maityamit
