### ISSUE TITLE
Documentation: 

### ISSUE THREAD

**Issue by sanjaygupta972004** [maityamit/Sleepometer-Android-App#81]
### Description

Hello sir/mam 
   I want to add process,workflow and aim of the project in README file

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by sanjaygupta972004** [comment]
@maityamit

**Comment by maityamit** [comment]
@sanjaygupta972004 
what you want to add ?

**Comment by sanjaygupta972004** [comment]
sir i want to add how the project is working,aim of the project and workflow @maityamit

**Comment by maityamit** [comment]
Okay @sanjaygupta972004

**Comment by maityamit** [comment]
@sanjaygupta972004 JGEC Winter of Code or IwOC ?

**Comment by sanjaygupta972004** [comment]
iwoc
