### ISSUE TITLE
Missing instruction for environment setup.

### ISSUE THREAD

**Issue by Poras-oss** [maityamit/Sleepometer-Android-App#82]
### Contact Details

shrivasporas@gmail.com

### Missing instruction for environment setup.
I want to fix this issue of missing instruction under JWOC

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maityamit** [comment]
@Poras-oss iwoc or Jwoc Please mention.

**Comment by Poras-oss** [comment]
> @Poras-oss iwoc or Jwoc Please mention.

I have mentioned the JWOC in the description.
