### ISSUE TITLE
Hindi Readme for multilinguals

### ISSUE THREAD

**Issue by A91y** [maityamit/Sleepometer-Android-App#87]
### Feature description

New Readme can be written in Hindi to help multilinguals.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by A91y** [comment]
Please assign me this issue under iwoc and easy/medium/hard.

**Comment by maityamit** [comment]
We don't need to do Hindi Readme. Sorry.
