### ISSUE TITLE
Feature: Add a attractive look at the bottom bar ⭐

### ISSUE THREAD

**Issue by Suryansh1720001** [maityamit/Sleepometer-Android-App#92]
Hey, @maityamit 

### Feature description

I want to add some attractiveness at the bottom bar - 
- Home
- Stats
- Setting  

I want to make that application attractive in terms of users view.

Kindly assign me this issue under IWOC (IWOC + Hard level) labels.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by maityamit** [comment]
@Suryansh1720001 any example or screenshot? 
means that you want to create , previous example ?

**Comment by Suryansh1720001** [comment]
Check this one with round corner 

![Screenshot_20230228_090412_Taaveez.jpg](https://user-images.githubusercontent.com/85965606/221746872-eaa5f522-0ee0-4cc6-b4ec-f05bce6af129.jpg)

**Comment by maityamit** [comment]
@Suryansh1720001 It will be on bottom na ?

**Comment by Suryansh1720001** [comment]
Check this one with round corner 

![Screenshot_20230228_090412_Taaveez.jpg](https://user-images.githubusercontent.com/85965606/221746872-eaa5f522-0ee0-4cc6-b4ec-f05bce6af129.jpg)

Yes

**Comment by maityamit** [comment]
Hmm gotta @Suryansh1720001 
okay, go ahead. 
I assign it now as a medium issue. After checking the code quality , I may change the category.

**Comment by Suryansh1720001** [comment]
This application shows so many errors without doing anything -

![image](https://user-images.githubusercontent.com/85965606/221833201-1ec220dc-8971-4dd7-9e2a-632658f1575a.png)
