### ISSUE TITLE
Add table of contents

### ISSUE THREAD

**Issue by dhruv-porwal** [maityamit/Sleepometer-Android-App#94]
### Description

Add table of contents in Read me file so that contributors and maintainers can get a overview about project in a nutshell.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I agree to follow this project's Code of Conduct

**Comment by dhruv-porwal** [comment]
Please assign this issue to me @maityamit

**Comment by Code1705** [comment]
I want to contribute to this issue ,kindly assign me under JWOC

**Comment by maityamit** [comment]
Hi, @Code1705 
ya continue with this...
